### ISSUE TITLE
egg_pair_bootstrap.sh中get_property函数使用会导致注释掉的配置依然生效

### ISSUE THREAD

**Issue by zapjone** [FederatedAI/eggroll#535]
![image](https://user-images.githubusercontent.com/19503929/130591922-7e0eaa4a-aaaa-49a2-bc84-98a92fbbf448.png)
建议使用awk进行修改：
awk -F '=' '{if($2!~/^#/) print $2}'

**Comment by maxwong** [comment]
Thank you for your response. We are looking into it :)
