### ISSUE TITLE
Processor in session meta is not valid

### ISSUE THREAD

**Issue by zzzcq** [FederatedAI/eggroll#555]
When expanding nodemanagers，new nodemanager pid column session_processor table = -1，and it still exists after removal.

And when eggroll.core.grpc.channel.keepalive.timeout.sec use default value 3600,  grpc timeout, try to turn it smaller , it works normally, why?

**Comment by Edwin-Xu** [comment]
> same problem, it recovers after removeing  external nodemanagers

**Comment by Edwin-Xu** [comment]
m
