### ISSUE TITLE
机器学习过程中参与方的数据如何处理

### ISSUE THREAD

**Issue by yang-shuaijun** [FederatedAI/eggroll#622]
您好，
机器学习过程中参与方的数据如何处理？
提交了fate flow job后，我计划使用使用几个参与方的数据，
问题1: 参与方是否会收到使用数据的申请：具体的表的名称，在job里使用的算子的列表？
问题2: 参与方的数据在通过roll_site读取到host，或者guest如何处理，是存储在本地，还是在cache了，读取过来的数据是否是加密的？

另外一个问题
通过fate flow客户端上传的数据是否会在本地加密？

非常感谢您抽出宝贵的时间来解答我的疑问。

**Comment by dylan-fan** [comment]
问题1： 开源版本没有申请这一个说法的。
问题2： rollsite 读取的表一般是计算过程用到的表（lmdb），任务结束后会自动清理掉。
用户上传的表，开源版本目前没有加密，如果需要，可以在开源版本基础上增加数据加密的插件。
