### ISSUE TITLE
route_table.json 更新是否需要重新启动 rollsite 服务？

### ISSUE THREAD

**Issue by awencai** [FederatedAI/eggroll#652]
如题，我在使用的过程中发现：
1. 有时 route_table.json 更新了，可以正常提交任务。
2. 有时候又不行，报: The touting table not have current party=xxxx，实际上对应的 partyID 存在与 route_table 中，并且ip 端口可以正常访问。这个时候就需要重新启动 rollsite 服务才行。

所以，针对上述遇到的情况就很疑惑：
1. 更新了route_table.json 是否需要重启 rollsite 服务
2. rollsite 启动的脚本返回结果之后实际上还在启动中，我能通过什么方式确定 rollsite 确实可用了？

感谢解答~

**Comment by awencai** [comment]
看了一下代码，不知道我理解得对不对哈。route_table  的更新机制是

**Comment by awencai** [comment]
看了一下代码不知道我理解得是否正确：

**Comment by awencai** [comment]
看了一下代码不知道我理解得是否正确:  route_table 的更新机制是固定 1min 去读取 route_table.json 配置文件来更新 router 信息。 <br> `Router.initOrUpdateRouterTable(routerFilePath), 1, 1, TimeUnit.MINUTES)`  <br> 这个就能说得通我上里面遇到的现象了，有的可以成功是正好遇到 rollsite 更新 router，有的不能成功是因为我还未等到下一个更新窗口到来，配置未生效。<br> 那么我这里有个新的问题，eggroll 是否有提供手动触发 router 更新的入口呢？

**Comment by dylan-fan** [comment]
目前最好的方式还是重启
