### ISSUE TITLE
添加合作方后可以不用重启rollsite容器就能实现多方之间的通讯吗?

### ISSUE THREAD

**Issue by 123fei1** [FederatedAI/eggroll#664]
目前我添加合作方后需要重启容器两方才能正常通讯, 否则就会报"Federated schedule error". 我用的fate是1.9.0版本一套源代码. 
我希望是在不重启的情况下就能与新添加的合作方发起通讯, 因为如果重启的话会出现我已经在运行的作业中间有五分钟会处于等待状态(不做功)五分钟后才继续执行,我就是想看看有没有在不重启的情况下还能与新添加的合作方做任务

**Comment by dylan-fan** [comment]
这里可以调整rollsite 读取配置时间的间隔。rollsite是定期重新读取路由表的。
