### ISSUE TITLE
能不能写一份比较详细的介绍eggroll的文档，介绍一下eggroll的模块、原理、接口和代码结构等，万分感谢。

### ISSUE THREAD

**Issue by GreyJeremyji** [FederatedAI/eggroll#707]
eggroll的文档太少了，阅读源码的成功太高了。

**Comment by dylan-fan** [comment]
可以参考eggroll 3.x 的文档，后面我们争取逐步完善文档。

**Comment by hust-suwb** [comment]
3.x除了一个部署文档也没有任何其他文档了呀。

> 可以参考eggroll 3.x 的文档，后面我们争取逐步完善文档。
